openapi: 3.0.3
info:
  title: Causa API
  version: 0.1.0
  description: API for issue tracking and phase workflows.
servers:
  - url: /
paths:
  /issues:
    post:
      tags:
        - Issues
      summary: Create a new issue
      operationId: createIssue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateIssueRequest'
      responses:
        '201':
          description: Issue created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IssueResponse'
    get:
      tags:
        - Issues
      summary: List issues
      operationId: listIssues
      parameters:
        - name: owner
          in: query
          required: false
          schema:
            type: string
        - name: assignee
          in: query
          required: false
          schema:
            type: string
        - name: member
          in: query
          required: false
          schema:
            type: string
        - name: projectId
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Issue list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IssueSummary'
  /issues/{issueId}:
    get:
      tags:
        - Issues
      summary: Get issue by id
      operationId: getIssue
      parameters:
        - name: issueId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Issue details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IssueResponse'
        '404':
          description: Issue not found
  /issues/{issueId}/owner:
    patch:
      tags:
        - Issues
      summary: Assign issue owner
      operationId: assignIssueOwner
      parameters:
        - name: issueId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssignOwnerRequest'
      responses:
        '200':
          description: Owner assigned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IssueResponse'
        '404':
          description: Issue not found
  /issues/{issueId}/phases:
    post:
      tags:
        - Issues
      summary: Add a phase to an issue
      operationId: addPhase
      parameters:
        - name: issueId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddPhaseRequest'
      responses:
        '200':
          description: Phase added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IssueResponse'
        '404':
          description: Issue not found
  /issues/{issueId}/phases/{phaseId}/assignee:
    patch:
      tags:
        - Issues
      summary: Assign a phase assignee
      operationId: assignPhaseAssignee
      parameters:
        - name: issueId
          in: path
          required: true
          schema:
            type: string
        - name: phaseId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssignAssigneeRequest'
      responses:
        '200':
          description: Assignee updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IssueResponse'
        '404':
          description: Issue or phase not found
  /issues/{issueId}/phases/{phaseId}/tasks:
    post:
      tags:
        - Issues
      summary: Add a task to a phase
      operationId: addTask
      parameters:
        - name: issueId
          in: path
          required: true
          schema:
            type: string
        - name: phaseId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddTaskRequest'
      responses:
        '200':
          description: Task added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IssueResponse'
        '404':
          description: Issue or phase not found
components:
  schemas:
    CreateIssueRequest:
      type: object
      required:
        - title
        - owner
        - phases
      properties:
        title:
          type: string
        owner:
          type: string
        projectId:
          type: string
        phases:
          type: array
          items:
            $ref: '#/components/schemas/CreatePhaseRequest'
    AssignOwnerRequest:
      type: object
      required:
        - owner
      properties:
        owner:
          type: string
    AssignAssigneeRequest:
      type: object
      required:
        - assignee
      properties:
        assignee:
          type: string
    AddPhaseRequest:
      type: object
      required:
        - name
        - assignee
      properties:
        name:
          type: string
        assignee:
          type: string
    AddTaskRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
        assignee:
          type: string
    CreatePhaseRequest:
      type: object
      required:
        - name
        - assignee
      properties:
        name:
          type: string
        assignee:
          type: string
    IssueResponse:
      type: object
      required:
        - id
        - title
        - owner
        - phases
        - version
      properties:
        id:
          type: string
        title:
          type: string
        owner:
          type: string
        projectId:
          type: string
        phases:
          type: array
          items:
            $ref: '#/components/schemas/PhaseResponse'
        version:
          type: integer
          format: int64
    IssueSummary:
      type: object
      required:
        - id
        - title
        - owner
        - phaseCount
        - status
      properties:
        id:
          type: string
        title:
          type: string
        owner:
          type: string
        projectId:
          type: string
        phaseCount:
          type: integer
          format: int32
        status:
          type: string
          enum:
            - NOT_STARTED
            - IN_PROGRESS
            - DONE
    PhaseResponse:
      type: object
      required:
        - id
        - name
        - assignee
        - status
        - tasks
      properties:
        id:
          type: string
        name:
          type: string
        assignee:
          type: string
        status:
          type: string
          enum:
            - NOT_STARTED
            - IN_PROGRESS
            - DONE
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/TaskResponse'
    TaskResponse:
      type: object
      required:
        - id
        - title
        - status
      properties:
        id:
          type: string
        title:
          type: string
        assignee:
          type: string
        status:
          type: string
          enum:
            - NOT_STARTED
            - IN_PROGRESS
            - DONE
