/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List issues */
        get: operations["listIssues"];
        put?: never;
        /** Create a new issue */
        post: operations["createIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{issueId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get issue by id */
        get: operations["getIssue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update issue metadata */
        patch: operations["updateIssue"];
        trace?: never;
    };
    "/issues/{issueId}/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign issue owner */
        patch: operations["assignIssueOwner"];
        trace?: never;
    };
    "/issues/{issueId}/actions/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close an issue */
        post: operations["closeIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{issueId}/phases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a phase to an issue */
        post: operations["addPhase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{issueId}/phases/{phaseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update phase */
        patch: operations["updatePhase"];
        trace?: never;
    };
    "/issues/{issueId}/phases/{phaseId}/assignee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign a phase assignee */
        patch: operations["assignPhaseAssignee"];
        trace?: never;
    };
    "/issues/{issueId}/phases/{phaseId}/actions/fail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark phase as failed */
        post: operations["failPhase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{issueId}/phases/{phaseId}/actions/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen phase */
        post: operations["reopenPhase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{issueId}/phases/{phaseId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a task to a phase */
        post: operations["addTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{issueId}/phases/{phaseId}/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update task */
        patch: operations["updateTask"];
        trace?: never;
    };
    "/issues/{issueId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get issue history */
        get: operations["getIssueHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{issueId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List issue comments */
        get: operations["listIssueComments"];
        put?: never;
        /** Add issue comment */
        post: operations["addIssueComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/work": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get per-user work queues */
        get: operations["getMyWork"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search issues */
        get: operations["searchIssues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateIssueRequest: {
            title: string;
            ownerId: string;
            projectId: string;
            phases: components["schemas"]["CreatePhaseRequest"][];
        };
        UpdateIssueRequest: {
            title?: string;
            ownerId?: string;
            projectId?: string;
        };
        AssignOwnerRequest: {
            ownerId: string;
        };
        AssignAssigneeRequest: {
            assigneeId: string;
        };
        AddPhaseRequest: {
            name: string;
            assigneeId: string;
            kind?: components["schemas"]["PhaseKind"];
        };
        UpdatePhaseRequest: {
            name?: string;
            assigneeId?: string;
            status?: components["schemas"]["PhaseStatus"];
            kind?: components["schemas"]["PhaseKind"];
        };
        AddTaskRequest: {
            title: string;
            assigneeId?: string;
        };
        UpdateTaskRequest: {
            title?: string;
            assigneeId?: string;
            status?: components["schemas"]["TaskStatus"];
        };
        CreatePhaseRequest: {
            name: string;
            assigneeId: string;
            kind?: components["schemas"]["PhaseKind"];
        };
        IssueListItem: {
            id: string;
            title: string;
            ownerId: string;
            projectId?: string;
            /** Format: int32 */
            phaseCount: number;
            status: components["schemas"]["IssueStatus"];
        };
        IssueDetail: {
            id: string;
            title: string;
            ownerId: string;
            projectId?: string;
            phases: components["schemas"]["PhaseResponse"][];
            status: components["schemas"]["IssueStatus"];
            /** Format: int64 */
            version: number;
            allowedActions?: {
                [key: string]: components["schemas"]["ActionDecision"];
            };
        };
        PhaseResponse: {
            id: string;
            name: string;
            assigneeId: string;
            status: components["schemas"]["PhaseStatus"];
            kind?: components["schemas"]["PhaseKind"];
            tasks: components["schemas"]["TaskResponse"][];
            allowedActions?: {
                [key: string]: components["schemas"]["ActionDecision"];
            };
        };
        TaskResponse: {
            id: string;
            title: string;
            assigneeId?: string;
            status: components["schemas"]["TaskStatus"];
            allowedActions?: {
                [key: string]: components["schemas"]["ActionDecision"];
            };
        };
        IssueHistoryResponse: {
            activity: components["schemas"]["ActivityEntry"][];
            audit: components["schemas"]["AuditEntry"][];
        };
        ActivityEntry: {
            id: string;
            issueId: string;
            type: string;
            summary: string;
            actorId?: string;
            /** Format: date-time */
            occurredAt: string;
        };
        AuditEntry: {
            id: string;
            issueId: string;
            entityType: string;
            entityId: string;
            changeType: string;
            actorId?: string;
            /** Format: date-time */
            occurredAt: string;
            fields?: {
                [key: string]: Record<string, never>;
            };
        };
        AddCommentRequest: {
            body: string;
            mentions?: string[];
        };
        CommentResponse: {
            id: string;
            issueId: string;
            authorId: string;
            body: string;
            /** Format: date-time */
            createdAt: string;
        };
        MyWorkResponse: {
            ownedIssues: components["schemas"]["IssueListItem"][];
            assignedPhases: components["schemas"]["PhaseWorkItem"][];
            assignedTasks: components["schemas"]["TaskWorkItem"][];
        };
        PhaseWorkItem: {
            issueId: string;
            phaseId: string;
            phaseName: string;
            status: components["schemas"]["PhaseStatus"];
        };
        TaskWorkItem: {
            issueId: string;
            phaseId: string;
            taskId: string;
            taskTitle: string;
            status: components["schemas"]["TaskStatus"];
        };
        ActionDecision: {
            allowed: boolean;
            reason?: string;
        };
        /** @enum {string} */
        IssueStatus: "CREATED" | "IN_ANALYSIS" | "IN_DEVELOPMENT" | "IN_TEST" | "IN_ROLLOUT" | "DONE" | "FAILED";
        /** @enum {string} */
        PhaseStatus: "NOT_STARTED" | "IN_PROGRESS" | "DONE" | "FAILED";
        /** @enum {string} */
        TaskStatus: "NOT_STARTED" | "IN_PROGRESS" | "DONE";
        /** @enum {string} */
        PhaseKind: "INVESTIGATION" | "PROPOSE_SOLUTION" | "DEVELOPMENT" | "ACCEPTANCE_TEST" | "ROLLOUT";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listIssues: {
        parameters: {
            query?: {
                ownerId?: string;
                assigneeId?: string;
                memberId?: string;
                projectId?: string;
                status?: components["schemas"]["IssueStatus"];
                phaseKind?: components["schemas"]["PhaseKind"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueListItem"][];
                };
            };
        };
    };
    createIssue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIssueRequest"];
            };
        };
        responses: {
            /** @description Issue created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
        };
    };
    getIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Issue not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIssueRequest"];
            };
        };
        responses: {
            /** @description Issue updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Issue not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    assignIssueOwner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignOwnerRequest"];
            };
        };
        responses: {
            /** @description Owner assigned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Issue not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    closeIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue closed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Issue not ready to close */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addPhase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddPhaseRequest"];
            };
        };
        responses: {
            /** @description Phase added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Issue not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updatePhase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
                phaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePhaseRequest"];
            };
        };
        responses: {
            /** @description Phase updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Issue or phase not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    assignPhaseAssignee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
                phaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignAssigneeRequest"];
            };
        };
        responses: {
            /** @description Assignee updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Issue or phase not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    failPhase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
                phaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Phase failed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Invalid transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reopenPhase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
                phaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Phase reopened */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Invalid transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
                phaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTaskRequest"];
            };
        };
        responses: {
            /** @description Task added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Issue or phase not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
                phaseId: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskRequest"];
            };
        };
        responses: {
            /** @description Task updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Issue, phase, or task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getIssueHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueHistoryResponse"];
                };
            };
            /** @description Issue not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listIssueComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comment list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"][];
                };
            };
        };
    };
    addIssueComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCommentRequest"];
            };
        };
        responses: {
            /** @description Comment added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"];
                };
            };
        };
    };
    getMyWork: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Work queues */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyWorkResponse"];
                };
            };
        };
    };
    searchIssues: {
        parameters: {
            query: {
                q: string;
                projectId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueListItem"][];
                };
            };
        };
    };
}
