/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List issues */
        get: operations["listIssues"];
        put?: never;
        /** Create a new issue */
        post: operations["createIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find similar issues */
        get: operations["findSimilarIssues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Faceted issue filters */
        get: operations["getIssueFacets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{issueId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get issue by id */
        get: operations["getIssue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update issue metadata */
        patch: operations["updateIssue"];
        trace?: never;
    };
    "/issues/{issueId}/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign issue owner */
        patch: operations["assignIssueOwner"];
        trace?: never;
    };
    "/issues/{issueId}/actions/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close an issue */
        post: operations["closeIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{issueId}/actions/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abandon an issue */
        post: operations["abandonIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{issueId}/phases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a phase to an issue */
        post: operations["addPhase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{issueId}/phases/{phaseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update phase */
        patch: operations["updatePhase"];
        trace?: never;
    };
    "/issues/{issueId}/phases/{phaseId}/assignee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign a phase assignee */
        patch: operations["assignPhaseAssignee"];
        trace?: never;
    };
    "/issues/{issueId}/phases/{phaseId}/actions/fail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark phase as failed */
        post: operations["failPhase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{issueId}/phases/{phaseId}/actions/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen phase */
        post: operations["reopenPhase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{issueId}/phases/{phaseId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a task to a phase */
        post: operations["addTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{issueId}/phases/{phaseId}/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update task */
        patch: operations["updateTask"];
        trace?: never;
    };
    "/issues/{issueId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get issue history */
        get: operations["getIssueHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{issueId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List issue comments */
        get: operations["listIssueComments"];
        put?: never;
        /** Add issue comment */
        post: operations["addIssueComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{issueId}/comments/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark issue comments as read */
        post: operations["markIssueCommentsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/work": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get per-user work queues */
        get: operations["getMyWork"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available authentication methods */
        get: operations["getAuthMethods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: operations["listProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List project facets */
        get: operations["getProjectFacets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign project owner */
        patch: operations["assignProjectOwner"];
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search issues */
        get: operations["searchIssues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream live updates via SSE */
        get: operations["streamUpdates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an organization */
        post: operations["createOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a team */
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/memberships/org": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add org membership */
        post: operations["addOrgMembership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/memberships/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add team membership */
        post: operations["addTeamMembership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/memberships/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add project membership */
        post: operations["addProjectMembership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateIssueRequest: {
            title: string;
            ownerId: string;
            projectId: string;
            description: string;
            /** Format: date */
            deadline?: string;
            phases: components["schemas"]["CreatePhaseRequest"][];
        };
        UpdateIssueRequest: {
            title?: string;
            ownerId?: string;
            projectId?: string;
            description?: string;
            /** Format: date */
            deadline?: string;
        };
        AssignOwnerRequest: {
            ownerId: string;
        };
        AssignAssigneeRequest: {
            assigneeId: string;
        };
        AddPhaseRequest: {
            name: string;
            assigneeId: string;
            kind?: components["schemas"]["PhaseKind"];
            /** Format: date */
            deadline?: string;
        };
        UpdatePhaseRequest: {
            name?: string;
            assigneeId?: string;
            status?: components["schemas"]["PhaseStatus"];
            completionComment?: string;
            /** Format: uri */
            completionArtifactUrl?: string;
            kind?: components["schemas"]["PhaseKind"];
            /** Format: date */
            deadline?: string;
        };
        AddTaskRequest: {
            title: string;
            assigneeId?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            dueDate?: string;
            dependencies?: components["schemas"]["TaskDependency"][];
        };
        UpdateTaskRequest: {
            title?: string;
            assigneeId?: string;
            status?: components["schemas"]["TaskStatus"];
            clearStartDate?: boolean;
            clearDueDate?: boolean;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            dueDate?: string;
            dependencies?: components["schemas"]["TaskDependency"][];
        };
        CreatePhaseRequest: {
            name: string;
            assigneeId: string;
            kind?: components["schemas"]["PhaseKind"];
            /** Format: date */
            deadline?: string;
        };
        IssueListItem: {
            id: string;
            title: string;
            description?: string;
            ownerId: string;
            projectId?: string;
            /** Format: int32 */
            phaseCount: number;
            phaseStatusCounts?: {
                [key: string]: number;
            };
            phaseProgress?: components["schemas"]["PhaseProgressItem"][];
            status: components["schemas"]["IssueStatus"];
            /** Format: date */
            deadline?: string;
        };
        IssueDetail: {
            id: string;
            title: string;
            description: string;
            ownerId: string;
            projectId?: string;
            phases: components["schemas"]["PhaseResponse"][];
            status: components["schemas"]["IssueStatus"];
            /** Format: date */
            deadline?: string;
            /** Format: int64 */
            version: number;
            allowedActions?: {
                [key: string]: components["schemas"]["ActionDecision"];
            };
        };
        PhaseProgressItem: {
            phaseId: string;
            phaseName: string;
            assigneeId: string;
            phaseKind?: components["schemas"]["PhaseKind"];
            /** Format: date */
            deadline?: string | null;
            status: components["schemas"]["PhaseStatus"];
            taskStatusCounts: {
                [key: string]: number;
            };
            /** Format: int32 */
            taskTotal: number;
        };
        IssueFacetOption: {
            id: string;
            /** Format: int32 */
            count: number;
        };
        IssueFacetResponse: {
            owners: components["schemas"]["IssueFacetOption"][];
            assignees: components["schemas"]["IssueFacetOption"][];
            projects: components["schemas"]["IssueFacetOption"][];
            statuses: components["schemas"]["IssueFacetOption"][];
            phaseKinds: components["schemas"]["IssueFacetOption"][];
        };
        PhaseResponse: {
            id: string;
            name: string;
            assigneeId: string;
            status: components["schemas"]["PhaseStatus"];
            kind?: components["schemas"]["PhaseKind"];
            completionComment?: string;
            /** Format: uri */
            completionArtifactUrl?: string;
            /** Format: date */
            deadline?: string;
            tasks: components["schemas"]["TaskResponse"][];
            allowedActions?: {
                [key: string]: components["schemas"]["ActionDecision"];
            };
        };
        TaskResponse: {
            id: string;
            title: string;
            assigneeId?: string;
            status: components["schemas"]["TaskStatus"];
            /** Format: date */
            startDate?: string;
            /** Format: date */
            dueDate?: string;
            dependencies?: components["schemas"]["TaskDependency"][];
            allowedActions?: {
                [key: string]: components["schemas"]["ActionDecision"];
            };
        };
        IssueHistoryResponse: {
            activity: components["schemas"]["ActivityEntry"][];
            audit: components["schemas"]["AuditEntry"][];
        };
        ActivityEntry: {
            id: string;
            issueId: string;
            type: string;
            summary: string;
            actorId?: string;
            /** Format: date-time */
            occurredAt: string;
        };
        AuditEntry: {
            id: string;
            issueId: string;
            entityType: string;
            entityId: string;
            changeType: string;
            actorId?: string;
            /** Format: date-time */
            occurredAt: string;
            fields?: {
                [key: string]: Record<string, never>;
            };
        };
        AddCommentRequest: {
            body: string;
            mentions?: string[];
        };
        CommentResponse: {
            id: string;
            issueId: string;
            authorId: string;
            body: string;
            /** Format: date-time */
            createdAt: string;
            readByCount?: number;
            unreadByCount?: number;
            readByUsers?: components["schemas"]["UserSummary"][];
            unreadByUsers?: components["schemas"]["UserSummary"][];
        };
        IssueCommentsResponse: {
            comments: components["schemas"]["CommentResponse"][];
            unreadCount: number;
            /** Format: date-time */
            lastReadAt?: string;
            /** Format: date-time */
            latestCommentAt?: string;
            firstUnreadCommentId?: string;
        };
        CommentReadRequest: {
            lastReadCommentId?: string;
        };
        CommentReadResponse: {
            /** Format: date-time */
            lastReadAt: string;
            unreadCount: number;
            /** Format: date-time */
            latestCommentAt?: string;
        };
        MyWorkResponse: {
            ownedIssues: components["schemas"]["IssueListItem"][];
            assignedPhases: components["schemas"]["PhaseWorkItem"][];
            assignedTasks: components["schemas"]["TaskWorkItem"][];
        };
        AuthMethodsResponse: {
            methods: components["schemas"]["AuthMethod"][];
        };
        AuthMethod: {
            type: string;
            label: string;
            authorizeUrl?: string;
        };
        ProjectSummary: {
            id: string;
            key: string;
            name: string;
            orgId: string;
            teamId: string;
            ownerId?: string | null;
            issueStatusCounts?: {
                [key: string]: number;
            };
            phaseStatusCounts?: {
                [key: string]: number;
            };
            phaseStatusByIssueStatus?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        ProjectFacetOption: {
            id: string;
            /** Format: int64 */
            count: number;
        };
        ProjectFacetResponse: {
            owners: components["schemas"]["ProjectFacetOption"][];
            teams: components["schemas"]["ProjectFacetOption"][];
        };
        AssignProjectOwnerRequest: {
            ownerId?: string | null;
        };
        UserSummary: {
            id: string;
            displayName: string;
            email?: string;
            /** Format: int64 */
            openIssueCount?: number;
            /** Format: int64 */
            openPhaseCount?: number;
            /** Format: int64 */
            openTaskCount?: number;
        };
        OrgSummary: {
            id: string;
            name: string;
        };
        TeamSummary: {
            id: string;
            orgId: string;
            parentTeamId?: string | null;
            name: string;
        };
        OrgMembershipSummary: {
            id: string;
            orgId: string;
            userId: string;
        };
        TeamMembershipSummary: {
            id: string;
            teamId: string;
            userId: string;
        };
        ProjectMembershipSummary: {
            id: string;
            projectId: string;
            userId: string;
        };
        CreateOrgRequest: {
            name: string;
        };
        CreateTeamRequest: {
            orgId: string;
            parentTeamId?: string | null;
            name: string;
        };
        CreateProjectRequest: {
            key: string;
            orgId: string;
            teamId: string;
            name: string;
        };
        CreateOrgMembershipRequest: {
            orgId: string;
            userId: string;
        };
        CreateTeamMembershipRequest: {
            teamId: string;
            userId: string;
        };
        CreateProjectMembershipRequest: {
            projectId: string;
            userId: string;
        };
        PhaseWorkItem: {
            issueId: string;
            phaseId: string;
            phaseName: string;
            status: components["schemas"]["PhaseStatus"];
        };
        TaskWorkItem: {
            issueId: string;
            phaseId: string;
            taskId: string;
            taskTitle: string;
            status: components["schemas"]["TaskStatus"];
        };
        ActionDecision: {
            allowed: boolean;
            reason?: string;
        };
        /** @enum {string} */
        IssueStatus: "CREATED" | "NOT_ACTIVE" | "IN_ANALYSIS" | "IN_DEVELOPMENT" | "IN_TEST" | "IN_ROLLOUT" | "DONE" | "FAILED";
        /** @enum {string} */
        PhaseStatus: "NOT_STARTED" | "IN_PROGRESS" | "DONE" | "FAILED";
        /** @enum {string} */
        TaskStatus: "NOT_STARTED" | "IN_PROGRESS" | "PAUSED" | "ABANDONED" | "DONE";
        TaskDependency: {
            /** @enum {string} */
            type: "TASK" | "PHASE" | "ISSUE";
            targetId: string;
        };
        /** @enum {string} */
        PhaseKind: "INVESTIGATION" | "PROPOSE_SOLUTION" | "DEVELOPMENT" | "ACCEPTANCE_TEST" | "ROLLOUT";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listIssues: {
        parameters: {
            query?: {
                ownerId?: string;
                query?: string;
                assigneeId?: string;
                memberId?: string;
                projectId?: string;
                status?: components["schemas"]["IssueStatus"];
                phaseKind?: components["schemas"]["PhaseKind"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueListItem"][];
                };
            };
        };
    };
    createIssue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIssueRequest"];
            };
        };
        responses: {
            /** @description Issue created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
        };
    };
    findSimilarIssues: {
        parameters: {
            query: {
                query: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Similar issues */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueListItem"][];
                };
            };
        };
    };
    getIssueFacets: {
        parameters: {
            query?: {
                query?: string;
                ownerId?: string;
                assigneeId?: string;
                memberId?: string;
                projectId?: string;
                status?: components["schemas"]["IssueStatus"];
                phaseKind?: components["schemas"]["PhaseKind"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Faceted options */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueFacetResponse"];
                };
            };
        };
    };
    getIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Issue not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIssueRequest"];
            };
        };
        responses: {
            /** @description Issue updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Issue not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    assignIssueOwner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignOwnerRequest"];
            };
        };
        responses: {
            /** @description Owner assigned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Issue not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    closeIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue closed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Issue not ready to close */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    abandonIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue abandoned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Issue not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addPhase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddPhaseRequest"];
            };
        };
        responses: {
            /** @description Phase added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Issue not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updatePhase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
                phaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePhaseRequest"];
            };
        };
        responses: {
            /** @description Phase updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Issue or phase not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    assignPhaseAssignee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
                phaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignAssigneeRequest"];
            };
        };
        responses: {
            /** @description Assignee updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Issue or phase not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    failPhase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
                phaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Phase failed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Invalid transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reopenPhase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
                phaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Phase reopened */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Invalid transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
                phaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTaskRequest"];
            };
        };
        responses: {
            /** @description Task added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Issue or phase not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
                phaseId: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskRequest"];
            };
        };
        responses: {
            /** @description Task updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Issue, phase, or task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getIssueHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueHistoryResponse"];
                };
            };
            /** @description Issue not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listIssueComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comment thread */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueCommentsResponse"];
                };
            };
        };
    };
    addIssueComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCommentRequest"];
            };
        };
        responses: {
            /** @description Comment added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"];
                };
            };
        };
    };
    markIssueCommentsRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CommentReadRequest"];
            };
        };
        responses: {
            /** @description Read state updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentReadResponse"];
                };
            };
        };
    };
    getMyWork: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Work queues */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyWorkResponse"];
                };
            };
        };
    };
    getAuthMethods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Auth methods */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMethodsResponse"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: {
                q?: string;
                orgId?: string;
                ownerId?: string;
                teamId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    getProjectFacets: {
        parameters: {
            query?: {
                q?: string;
                orgId?: string;
                ownerId?: string;
                teamId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project facet response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectFacetResponse"];
                };
            };
        };
    };
    assignProjectOwner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignProjectOwnerRequest"];
            };
        };
        responses: {
            /** @description Updated project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"];
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: {
                q?: string;
                projectId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"][];
                };
            };
        };
    };
    searchIssues: {
        parameters: {
            query: {
                q: string;
                projectId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueListItem"][];
                };
            };
        };
    };
    streamUpdates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    createOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrgRequest"];
            };
        };
        responses: {
            /** @description Org created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgSummary"];
                };
            };
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamRequest"];
            };
        };
        responses: {
            /** @description Team created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamSummary"];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Project created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"];
                };
            };
        };
    };
    addOrgMembership: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrgMembershipRequest"];
            };
        };
        responses: {
            /** @description Org membership created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgMembershipSummary"];
                };
            };
        };
    };
    addTeamMembership: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamMembershipRequest"];
            };
        };
        responses: {
            /** @description Team membership created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMembershipSummary"];
                };
            };
        };
    };
    addProjectMembership: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectMembershipRequest"];
            };
        };
        responses: {
            /** @description Project membership created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMembershipSummary"];
                };
            };
        };
    };
}
